### ISSUE TITLE
Release new version with updated dependencies?

### ISSUE THREAD

**Issue by ajssd** [lazd/gulp-replace#108]
The dependencies of gulp-replace have been updated many times since gulp-replace 1.0.0 was released.  Is it possible to release a new version of gulp-replace that picks up the latest versions of its dependencies?

**Comment by lazd** [comment]
@ajssd sure, would take a PR with updated deps.

**Comment by ajssd** [comment]
I created https://github.com/lazd/gulp-replace/pull/109 -- the unit tests seem to pass, but I assume you will want to have a closer look to make sure there are no other issues.  @lazd

**Comment by lazd** [comment]
Superseded by #111 , thanks!
