### ISSUE TITLE
Does not support regular expression horizontal space (\h)

### ISSUE THREAD

**Issue by ve3** [lazd/gulp-replace#110]
`"gulp-replace": "^1.0.0",`

Target file content:
```
Version: 1.1.0
```

Code:
```
let themeVersion = '1.2.3';
let regExp = new RegExp(/^(Version:)(\h*)([0-9a-z\.-]+)/, 'im');
tasks[1].pipe(replace(regExp, '$1$2' + themeVersion));
```

Expect result:
```
Version: 1.2.3
```

Get:
```
Version: 1.1.0
```
(no change)

Change pattern from `(\h*)` to `(\s*)` works fine.

**Comment by lazd** [comment]
Yup, because JavaScript regular expressions don't support `\h`: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions/Character_Classes
