### ISSUE TITLE
Version 1.1.0 breaks typescript imports

### ISSUE THREAD

**Issue by schw4rzlicht** [lazd/gulp-replace#117]
Hey there,

my gulpfile is written in Typescript and `gulp-replace` is used like this:

```typescript
import replace from "gulp-replace";

function doSomething() {
  return gulp.src("directory/*.html")
    .pipe(replace("string", "anotherString"))
    .pipe(gulp.dest("anotherDirectory"));
}

exports.build = gulp.series(doSomething);
```

After upgrading to `~1.1.0`, this breaks with

```
gulpfile.ts:46:35 - error TS2349: This expression is not callable.
  Type 'typeof import("<somePath>/node_modules/gulp-replace/index")' has no call signatures.
```

I also tried

```typescript
import { replace } from "gulp-replace";
import * as replace from "gulp-replace";
```

but without success 😕 

Any help appreciated!

**Comment by lazd** [comment]
Does #114 fix it?

**Comment by schw4rzlicht** [comment]
> Does #114 fix it?

Oh, I only searched for issues related to my problem. The PR you mentioned deals with exactly the problem I am facing.

**Comment by lazd** [comment]
@schw4rzlicht no problem, can you review/test that PR and see if it fixes the issue? Clone the repository locally, check out that branch, run `npm link` inside of it, then in your project `npm link gulp-replace`. When done testing, run `npm unlink gulp-replace` in your project.

**Comment by lazd** [comment]
@schw4rzlicht fixed in 1.1.2, give it a spin

**Comment by schw4rzlicht** [comment]
Works now. I have to import it like this now

```typescript
import replace = require("gulp-replace");
```

which looks a bit unfamiliar but is no problem at all. Thank you very much!

**Comment by lazd** [comment]
@schw4rzlicht thanks for reporting back! Yeah, it's a default export, so that makes sense
