### ISSUE TITLE
Tag v1.1.0 points to the wrong commit

### ISSUE THREAD

**Issue by Pustur** [lazd/gulp-replace#118]
I think `v1.1.0` should point to commit 7d5874fb9e65a5da05e60fd08cc58724109ad13a

As it is now tags `v1.1.0` and `v1.1.1` point to the same commit ba5b08d4ce1543dcdd041132b06dcc5b1e81b281

**Comment by lazd** [comment]
Fixed, thanks!

**Comment by Pustur** [comment]
Thanks.  
Just a heads up, you released `v1.1.2` under the name `1.1.1` here on GitHub 😝

**Comment by lazd** [comment]
It's too early to be doing releases hahah. Thanks!
