### ISSUE TITLE
Broken types

### ISSUE THREAD

**Issue by wszydlak** [lazd/gulp-replace#122]
Hi, types seems to be still invalid. If you use gulp-replace with typescript in version 1.1.2 it throws error:

```
Only ECMAScript imports may use 'import type'.

1 /// <reference types="node" />
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2 import type File = require("vinyl");
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ```
 
 Seems that for type imports you cannot use `require`, so code should look like:
 
 ```
 /// <reference types="node" />
import File = require("vinyl");
```

OR:

```
/// <reference types="node" />
import type * as File from "vinyl";
```

It looks like d.ts files not need `type` imports, so first solution could be better.

**Comment by lazd** [comment]
Fixed in 1.1.3!
