### ISSUE TITLE
not working when output length equals source length

### ISSUE THREAD

**Issue by gregmatys** [lazd/gulp-replace#128]
```
gulp
    .src(sourcepath)
    .pipe(replace(/content="1"/g, 'content="2"'))
    .pipe(gulp.dest(outputDestination));
```
When I try to replace string where output length equals source length, it doesn't not working...
And if I change this to `.pipe(replace(/content="1"/g, 'content="2"'))` it does work.

Reaally strange.. Am I missing something?

**Comment by gregmatys** [comment]
It's not the plugin issue itself.
That was VSCode that wasn't refreshing the file :/

**Comment by lazd** [comment]
Doh! Glad you figured it out!
