### ISSUE TITLE
Wrong output when replacement string contains '$'

### ISSUE THREAD

**Issue by jbe456** [lazd/gulp-replace#28]
I get a wrong output if the replacement string contains the following string `'$'`.

Example :
Input : 
```javascript
BEGIN
TOKEN
END
```

Gulp file :
```javascript
var replacement = '\'$\'';
... replace(/TOKEN/g, replacement) ...
```
Output :
```javascript
BEGIN
'
END
END
```

Using Gulp 3.8.10, and latest gulp-replace (0.5.0 of November the 14th 2014)

Meanwhile, I workaround the issue by replacing `'$'` by `String.fromCharCode(36)` in the replacement string.

**Comment by lazd** [comment]
This is standard behavior, so I'm closing this issue.
