### ISSUE TITLE
When replacestream is used replace function is passed array of matches

### ISSUE THREAD

**Issue by nlundquist** [lazd/gulp-replace#30]
As per the replacestream docs (https://github.com/eugeneware/replacestream) the replacement function is passed an array of matches rather than being called with the matches as parameters, the behaviour of String.replace. 

Gulp-replace implies in its documentation that the String.replace behaviour should be expected despite this being false when replacestream is used. This can't be expected by the user. When using replacestream gulp-replace should wrap the replacement function so that the array is converted into parameters for the wrapped function.

**Comment by mehtaphysical** [comment]
Maybe this is something i should change with replacestream. I think it is easier if everything is consistent with String.replace

**Comment by lazd** [comment]
Hmm, I agree we should definitely be consistent between a regex match on a stream and on a buffer.

@mehtaphysical @eugeneware, what do you think?

**Comment by mehtaphysical** [comment]
I'm willing to make that change. I wonder what @eugeneware thinks. https://github.com/eugeneware/replacestream/issues/15

**Comment by eugeneware** [comment]
It's ok by me. Consistency and ease of use should trump compatibility. :+1:

**Comment by lazd** [comment]
@eugeneware @mehtaphysical any timeline on getting this made consistent? I'm thinking a temporary workaround as suggested by @nlundquist is in order until it's changed in `replacestream`.

**Comment by mehtaphysical** [comment]
@lazd it's a pretty easy change. I'll write it this weekend and let @eugeneware review it.

**Comment by lazd** [comment]
Sounds great, thanks!

**Comment by eugeneware** [comment]
Sounds like a plan! :-)

**Comment by mehtaphysical** [comment]
@lazd done :)

**Comment by lazd** [comment]
Released as `gulp-replace@0.5.2`.
