### ISSUE TITLE
Bug in istextorbinary causing error in gulp-replace

### ISSUE THREAD

**Issue by bradbenvenuti** [lazd/gulp-replace#32]
Temporary solution is to install istextorbinary 1.0.0
`npm install istextorbinary@1.0.0`

https://github.com/bevry/istextorbinary/issues/3#issuecomment-70146637

**Comment by lazd** [comment]
This was already fixed and a new version of `gulp-replace` was released about an hour ago. I changed `gulp-replace` from using `"istextorbinary": "^1.0.0"` to `"istextorbinary": "1.0.0"
