### ISSUE TITLE
Replace makes task hang indefinately.

### ISSUE THREAD

**Issue by worldspawn** [lazd/gulp-replace#39]
I'm trying to use replace but the task never ends. 

``` javascript
gulp.task('importmodules', function () {
  var modules = require('./data/applicationModules.json');
  var moduleDependenciesRegex = /\/\/ replace:moduleDependencies\s+(?:\s*.+\s*)+\s+\/\/ endreplace/;
  var replaceWith = 'var moduleDependencies = ' + JSON.stringify(modules) + ';';
  replaceWith = '// replace:moduleDependencies\n\t' + replaceWith +  '\n\t// endreplace';

  return gulp.src('app/src/app.js')
    .pipe($.replace(moduleDependenciesRegex, '// replace:moduleDependencies\n\t' + replaceWith +  '\n\t// endreplace'))
    .pipe(gulp.dest('app/src'));
});
```

I see starting 'importmodules' and nothing after that. If i comment the replace line the task completes.

**Comment by nfantone** [comment]
+1

I have experienced this same issue today. Task just hangs indefinitely. Removing `$.replace` calls makes everything go back to normal. Gonna take a look into it and see what I can gather.

**Comment by nfantone** [comment]
Ok, it was a case of poorly written regexp for me. Just replaced a `*` for `+` and everything went smoothly.
