### ISSUE TITLE
Error: EISDIR

### ISSUE THREAD

**Issue by XavierDupessey** [lazd/gulp-replace#41]
Hi,

I get the following error:

events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: EISDIR, open '/Volumes/Data/Developpement/Sites web/Page perso - Wordpress/wp-content/themes/xavier/header.php'
    at Error (native)

With this config:

    var PROJECT_SRC_PATH = 'xavier.DEV',
        PROJECT_DST_PATH = 'xavier';
    
    gulp.task('test', function() {
        gulp.src(PROJECT_SRC_PATH + '/header.php')
        .pipe(replace('foo', 'bar'))
        .pipe(gulp.dest(PROJECT_DST_PATH + '/header.php'));
    });

Any idea ?

Thank you in advance

**Comment by lazd** [comment]
Is header.php a folder? That error usually means we're trying to read a file, but got a folder.

**Comment by XavierDupessey** [comment]
No, it is just an existing PHP file that I want to overwrite

"""
Xaviers-MacBook-Pro:xavier Xavier$ pwd
/Volumes/Data/Developpement/Sites web/Page perso - Wordpress/wp-content/themes/xavier
Xaviers-MacBook-Pro:xavier Xavier$ 
Xaviers-MacBook-Pro:xavier Xavier$ ls -l
total 136
-rwxr-xr-x   1 Xavier  staff    208 26 fév 19:25 404.php
-rwxr-xr-x   1 Xavier  staff    933 26 fév 19:25 comments.php
-rwxr-xr-x   1 Xavier  staff    929 26 fév 19:25 content.php
drwxr-xr-x   5 Xavier  staff    170 26 fév 19:25 fonts
-rwxr-xr-x   1 Xavier  staff    200 26 fév 19:25 footer.php
-rwxr-xr-x   1 Xavier  staff   7112 26 fév 19:25 functions.php
-rwxr-xr-x   1 Xavier  staff   3323 26 fév 19:25 header.php
drwxr-xr-x  11 Xavier  staff    374 26 fév 19:25 images
-rwxr-xr-x   1 Xavier  staff   1346 26 fév 19:25 index.php
-rwxr-xr-x   1 Xavier  staff    253 26 fév 19:25 page.php
drwxr-xr-x   7 Xavier  staff    238 26 fév 19:25 scripts
-rwxr-xr-x   1 Xavier  staff    167 26 fév 19:25 searchform.php
-rwxr-xr-x   1 Xavier  staff    681 26 fév 19:25 sidebar.php
-rwxr-xr-x   1 Xavier  staff    317 26 fév 19:25 single.php
-rwxr-xr-x   1 Xavier  staff  17942 26 fév 19:25 style.css
"""

**Comment by lazd** [comment]
Try this:

```js
var PROJECT_SRC_PATH = 'xavier.DEV',
    PROJECT_DST_PATH = 'xavier';

gulp.task('test', function() {
    gulp.src(PROJECT_SRC_PATH + '/header.php')
    .pipe(replace('foo', 'bar'))
    .pipe(gulp.dest(PROJECT_DST_PATH));
});
```

This is basically what the [`inplace` example](https://github.com/lazd/gulp-replace/tree/master/examples/inplace) does.

**Comment by XavierDupessey** [comment]
Ok you're right, sorry and thank you!
