### ISSUE TITLE
Replacement of multiple matches

### ISSUE THREAD

**Issue by malinky** [lazd/gulp-replace#44]
Hi, I'm trying to replace multiple instances of a match using a function as the replacement but it only replaces the first match so I'm not sure I have written it correctly could you take a look please. Thanks

```
gulp.task('dev-css-cache-buster', function() {
return gulp.src('../dev/header.php')
.pipe(replace(/style.css/, function() {
return 'style.' + Date.now() + '.css';
}))
.pipe(gulp.dest('../dev'));
})
```

**Comment by lazd** [comment]
This is regex 101, you need the global modifier. [/styles.css/g](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp#Parameters).

**Comment by malinky** [comment]
That's great thanks for helping out so quickly.
