### ISSUE TITLE
Question: How to create a task which create a new file name after replacement? 

### ISSUE THREAD

**Issue by daruwanov** [lazd/gulp-replace#46]
Hi. Sorry for my bad English.

```javascript
gulp.task('make-config', function(){
  gulp.src('www/js/_config.js')
    .pipe(replace("%APP_TOKEN%", gutil.env.APP_TOKEN))
    .pipe(replace("%API_URL%", gutil.env.API_URL))
    .pipe(gulp.dest('www/js/config.js'));
});
```
before running task i have file _config.js, and after task complete i want to have config.js file.

But it's create  `config.js` directory and in this directory  `_config.js` file, withh all replaced data.

Thanks.

**Comment by lazd** [comment]
This has nothing to do with `gulp-replace`.

https://www.npmjs.com/package/gulp-rename

https://www.npmjs.com/package/gulp-out
