### ISSUE TITLE
stable release

### ISSUE THREAD

**Issue by keradus** [lazd/gulp-replace#48]
Any chances for stable release (like v1.0.0) ?

**Comment by lazd** [comment]
Yeah, it's getting to be about that time. I don't see much changing any time soon...

**Comment by keradus** [comment]
Yeah, I see that this looks quite stable, so it would be great to have it released as stable as well!

**Comment by keradus** [comment]
@lazd, it would be cool to make it happen ;)

**Comment by keradus** [comment]
anyone ? :(

**Comment by lazd** [comment]
I'd like to see #50 closed first as it is a very important feature for many use cases and will change the function signature of replace functions.
