### ISSUE TITLE
Some File which skipBinary is "true", would not be replaced 

### ISSUE THREAD

**Issue by abcdefe** [lazd/gulp-replace#51]
```javascript
gulp.src(['**/*', '!./beta', '!./beta/**/*'])
    .pipe(replace(new RegExp('{{{filepath}}}', 'g'), 'beta', {skipBinary: true}))
    .pipe(gulp.dest('beta/'));
```

if i set skipBinary,  the chars in some file would not be replaced correctly.

![image](https://cloud.githubusercontent.com/assets/534022/8307502/43ccf256-19f1-11e5-8477-02832e640efd.png)

**Comment by lazd** [comment]
Can you give an example of a file where this happens? If it's not being replaced at all, I would assume that's due to istextorbinary misidentifying the file...

**Comment by abcdefe** [comment]
The environment is  my workspace folder contains lots of js,html,css and some pictures. SkipBinary skip the pics but some html files not replace.

-------------------------------------------------

I set a Reg rules in this html files.
![image](https://cloud.githubusercontent.com/assets/534022/8399949/d4b53330-1e49-11e5-9231-dc3dfb1764a3.png)

then run gulp 
![image](https://cloud.githubusercontent.com/assets/534022/8399971/14c501c6-1e4a-11e5-99e1-a11ca4126559.png)
![image](https://cloud.githubusercontent.com/assets/534022/8399979/3171316e-1e4a-11e5-8e3d-eceaaca1a30b.png)

the results
![image](https://cloud.githubusercontent.com/assets/534022/8400000/68fd1792-1e4a-11e5-8df9-1409a0e752e8.png)

but 
![image](https://cloud.githubusercontent.com/assets/534022/8400010/7bceab1a-1e4a-11e5-82a7-6404ed3153c3.png)

I guess there`s sth wrong when i use multiple folders .

**Comment by lazd** [comment]
Don't you think the glob might be wrong? It's matching every single file and using exclusion patterns (blacklist). Why not match only the files you want to run the replace on (whitelist)?

Try that first.

If it still doesn't work, please narrow it down to a *single file* that isn't being replaced, give the absolute path to that file in your gulpfile, and run it with/without `skipBinary`. If you can find a single file that `skipBinary` skips that it isn't supposed to, then create a git repo with the file and your gulpfile so I can troubleshoot it.

**Comment by abcdefe** [comment]
It should be something wrong with my config file, after I wrote a demo for test. sorry for bother.
