### ISSUE TITLE
Multiline Regex

### ISSUE THREAD

**Issue by JaredSartin** [lazd/gulp-replace#58]
I am looking to basically do 2 builds using an ifdef style commenting. I can't seem to get multiline regex definitions working. I have done multiple tests that my regexs are not at fault, is there a trick to this or is it not supported?

**Comment by krschmidt** [comment]
I had some trouble with multiline regex as well, but it those got fixed when I switched the . for [^] as reported in the documentation at https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp, under character classes. In my case, `.pipe(replace(/<script>[^]*<\/script>/g, "<script>\n" + replacement + "\n</script>"))` does do a multiline regex replace.

**Comment by lazd** [comment]
Looks like `[^]` is the answer @JaredSartin was looking for.
