### ISSUE TITLE
Allow base folder to be renamed. 

### ISSUE THREAD

**Issue by derekgreer** [lazd/gulp-replace#59]
http://stackoverflow.com/questions/32261944/how-can-the-base-directory-be-replaced-with-gulp/32262036#32262036

**Comment by lazd** [comment]
I don't understand the issue based on your post, but this probably isn't `gulp-replace`'d responsibility.

**Comment by derekgreer** [comment]
Basically, I'm looking to change the files matched by "src/**/*.js" into paths like "dest/**/*.js.  So for example, I'd like to do a gulp.src("src/**/*.js") which results in a file "src/somefolder/somefile.js" and change it to "dest/somefolder/somefile.js".  It would seem like gulp-rename should be able to do this since it gives you access to change the file's path property, but setting file.path = "dest" + file.path ends up with src\dest\somefolder\somefile.js.  The part before the glob doesn't seem to be able to be altered.

**Comment by lazd** [comment]
Closing as this isn't `gulp-replace`'s responsibility.
