### ISSUE TITLE
Conflict with gulp-postcss

### ISSUE THREAD

**Issue by Sigizmund2012** [lazd/gulp-replace#60]
Hello! I try to use yours plugin with gulp-postcss and occured error: [object Object] is not a PostCSS plugin. The gulp-postcss developer answer to my that it problem maybe in your plugin. 
My gulpfile.js
```
var gulp = require('gulp'),
	postcss = require('gulp-postcss'),
	replace = require('gulp-replace');
 
gulp.task('templates', function(){
  gulp.src(['css/*.css'])
    .pipe(postcss([replace(/\.\.\//g, '')]))
    .pipe(gulp.dest('build/'));
});

gulp.task('default', ['templates']);
```

**Comment by lazd** [comment]
That's not how you use a gulp plugin. Please read the gulp docs, specifically file streams and the concept of  `pipe()`.`
