### ISSUE TITLE
EventEmitter memory leak detected

### ISSUE THREAD

**Issue by jonathanasquier** [lazd/gulp-replace#61]
I'm having a `(node) warning: possible EventEmitter memory leak detected. 11 end listeners added. Use emitter.setMaxListeners() to increase limit.` using gulp-replace with usemin with node v4.1.1.

**Comment by lazd** [comment]
I can't imagine that this is related to gulp-replace at all. Please try to reproduce this problem with only gulp-replace in the stream and re-open the issue if you're successful.
