### ISSUE TITLE
Multiple Replace Operations

### ISSUE THREAD

**Issue by RehanSaeed** [lazd/gulp-replace#62]
Is it possible to do multiple find and replace operations with this plugin a bit like how [gulp-batch-replace](https://www.npmjs.com/package/gulp-batch-replace) works?

```
var replacements = [
    [ 'original', 'replacement' ],
    [ 'original1', 'replacement1' ],
    [ 'original2', 'replacement2' ]
    // ...N number of replacements.
];

var replace = require('gulp-replace');
 
gulp.task('templates', function(){
  gulp.src(['file.txt'])
    .pipe(replace(??????????))  // What do I do here?
    .pipe(gulp.dest('build/file.txt'));
});

```

**Comment by chebum** [comment]
Hi Rehan,

I believe the easiest way is to simply pipe several tasks like this:
.pipe(replace('original', 'replacement'))
.pipe(replace('original1', 'replacement1'))
.pipe(replace('original2', 'replacement2'))

**Comment by RehanSaeed** [comment]
What if you don't know the number of times you want to do a replace? I have an array of items I want to find and replace.

**Comment by chebum** [comment]
@RehanSaeed you can iterate your replace array like this.
var replaces = [...];   // Your replace array
var task = gulp.src(...);  // Your task
replaces.forEach(function(rep) {
 task = task.pipe(replace(rep));
});

**Comment by RehanSaeed** [comment]
That breaks the Gulp pipeline flow.

**Comment by jbnv** [comment]
I will +1 on adding the ability to specify an array of replacement options. In my particular case, the replacement happens in the middle of a series of `pipe`s. It's a very logical modification to make. I may pull and work on it myself.

**Comment by hustcer** [comment]
+1

**Comment by hustcer** [comment]
I suggest reopen this issue, for better batch replace performance and 'Write less, do more.' IMHO.

**Comment by lazd** [comment]
Let me play devil's advocate here: Why should a plugin implement support for repeating itself? It can easily be done with a single function written outside of the plugin, and that same function could be applied to any gulp plugin. Given that the notion of repeating a plugin with different input can be written in a generic way, should every gulp plugin for which repeating itself makes sense separately implement the ability to repeat itself, or should this be a gulp-friendly helper (or perhaps a plugin itself?) that accomplishes this and can be applied anywhere?

**Comment by lazd** [comment]
Also, is `gulp-replace` currently a bottleneck when performing multiple replace operations?

I would appreciate it if we could first demonstrate that performance is currently lacking or that the proposed change would increase performance before bringing it into the dialogue.

That said, I don't believe it's possible to achieve measurably better performance by doing the repetition within the plugin. Feel free to prove this one way or another with benchmarks, however!

**Comment by RehanSaeed** [comment]
> It can easily be done with a single function written outside of the plugin

Yes it's very easy to use a foreach but that breaks the Gulp pipeline. Gulp is all about the pipeline, flowing from one task to another. Breaking that flow so you can do a foreach is ugly.

**Comment by AllenBird** [comment]
+1

**Comment by futurist** [comment]
+1 for this feature!

**Comment by printempw** [comment]
+1

**Comment by nicothin** [comment]
+1 for this feature!

**Comment by b0o** [comment]
+1

>  It can easily be done with a single function written outside of the plugin

Can we get an example of this? I'm ending up doing some complex stuff with `through2` to try and accomplish this but it's a bit confusing.

**Comment by landsman** [comment]
+ 1

**Comment by pedrokehl** [comment]
+1

**Comment by dougiefresh49** [comment]
I was able to accomplish the multiple replaces very easily with the pseudo code from @chebum 

here is a more fleshed out example:

```
gulp.task('inject:mock-data', () => {
  let mockData = JSON.parse(fs.readFileSync('./data.json'));

  let task = gulp.src('./dist/*.html');

  Object.keys(data).forEach((key) => {
    task = task.pipe(replace(`{{${key}}}`, data[key]));
  });

  return task.pipe(gulp.dest('./dist'));
});
```

hope this helps

**Comment by akupaka** [comment]
@dougiefresh49 , it helped! Thx!
ps: isn't there an error in your example when you use `data` instead of `mockData`?
