### ISSUE TITLE
Add a Junk code for Japanese characters in my html file

### ISSUE THREAD

**Issue by berdejitendra14** [lazd/gulp-replace#72]
I have group of files which have Japanese characters. After running gulp replace, it convert all Japanese characters to junk characters (code). Do we have a solution for this?

**Comment by berdejitendra14** [comment]
Quick update - I converted my file to UTF8 and replacement work fine.

**Comment by lazd** [comment]
You might try https://www.npmjs.com/package/gulp-convert-encoding inline. What OS are you on? What version of Node? What version of gulp? How are the files encoded already?
