### ISSUE TITLE
add an optional third argument, options.default

### ISSUE THREAD

**Issue by lmj0011** [lazd/gulp-replace#78]
**feature request**

In case the replacement string is `null`/`empty string`, the default string would be used instead

```js
.pipe(replace('process.env.ENVIRONMENT', process.env.ENVIRONMENT, {default: 'production'}))
```

**Comment by lazd** [comment]
This can be accomplished with simple OR operator, there is no need to add an option for this.

`.pipe(replace('process.env.ENVIRONMENT', process.env.ENVIRONMENT || production))`
