### ISSUE TITLE
skipBinary option should be true by default

### ISSUE THREAD

**Issue by alexbain** [lazd/gulp-replace#81]
I ran into an issue where `gulp-replace` was trying to parse binary files in my project, which lead me to discover the `skipBinary` option. This is set to `false`, by default.

Why is a string replacement library trying to parse binary files, by default? I can't think of a use case where this is a sensible default. It seems far more sane to have `skipBinary` be `true` by default and, if someone needs to parse binary files, they adjust that setting to `false`.

**Comment by lazd** [comment]
I would imagine that your globs would only target files you want to perform
a replacement on. `skipBinary`, to me, is a way of letting people be lazy
with their globs.

What are your thoughts on that?

**Comment by alexbain** [comment]
Hi @lazd - I do see your point, but my thought is that binary files are very rarely files you perform string replacements on. In my case, the string replacement was corrupting all of my binary files. 

Since replacing strings in binary files is a "risky" operation, and something I'd imagine people are attempting only under specific circumstances, it seems generally safer to make users to opt in to that setting. This way, users are less likely to shoot themselves in the foot and can be lazy with their globs.

**Comment by lazd** [comment]
I agree, very few use cases need to perform a string replacement in a binary file.

Changing `skipBinary` to `true` by default would result in a major version increase. There are some other things we're considering, such as #50, that may require breaking API changes, so if this is done, it should be done at the same time.

**Comment by alexbain** [comment]
That makes sense, and I agree it would be a major version increase. Thank you for considering!

**Comment by abdonrd** [comment]
Any news on that? I also have the corrupting binary files issue.

**Comment by lazd** [comment]
@abdonrd then set `skipBinary: true`...

**Comment by lazd** [comment]
1.0.0 released with `skipBinary: true` by default.
