### ISSUE TITLE
cann't use Regex to replace 

### ISSUE THREAD

**Issue by mirkcale** [lazd/gulp-replace#83]
I want use regex to find something to be replace ,but It seems doesn't work.

this is my gulpfile
`gulp.task('test',function () {
    gulp.src(['./src/js/test.js'],{'base':'.'})
       .pipe(replace(/http:\/\/(\S*)v1\/$/,'lol'))
       .pipe(gulp.dest('dist'));
});``

this is the test javascript file

`var a = "http://192.168.199.122:8080/icar/v1/";
var b = '"http://192.168.199.116:8080/icar/v1/"';
var c = 'http://192.168.199.177:8080/icar/v1/';

**Comment by lazd** [comment]
This is a regex question and has nothing to do with the plugin, so I'm going to close this issue.

That said, `/` is a special character and you need to escape it with `\/`.

**Comment by mirkcale** [comment]
sorry ，I made this mistake

**Comment by mirkcale** [comment]
![image](https://cloud.githubusercontent.com/assets/19788310/23192351/eca32040-f8dd-11e6-8a08-47e7823cbd27.png)
sorry，due to the md ，exactly this picture was my RegEx.
