### ISSUE TITLE
Remove html code without generate a line break. 

### ISSUE THREAD

**Issue by hive-4-apps** [lazd/gulp-replace#86]
when I use this code to remove styles in <head> of html file : 
`.pipe(replace(stylesTag, ''))`
The code is removed but, it generates a breakline for any reason.
Someone has an idea ?
Is it a bug ?

**Comment by lazd** [comment]
What is the value of `stylesTag`? Try including a `\n` at the end of it.

**Comment by hive-4-apps** [comment]
Thank you very much ! .pipe(replace(stylesTag + '\n', '')) is the solution.
