### ISSUE TITLE
Set skipBinary: true by default

### ISSUE THREAD

**Issue by pensierinmusica** [lazd/gulp-replace#91]
Hi,

When I apply `gulp-replace` to a folder containing a jpeg or a png file, the resulting file is broken. For example:

```js
gulp.task('something',  () => {
  del.sync('dist');
  return gulp.src('**')
    .pipe($.replace(/^YOUR_UNIQUE_STRING$/gm, ''))
    .pipe(gulp.dest('dist'));
});
```

Smaller files are not affected though, and just for sanity check the same procedure without `gulp-replace` works fine (jpegs and pngs are not broken).

```js
gulp.task('something',  () => {
  del.sync('dist');
  return gulp.src('**')
    .pipe(gulp.dest('dist'));
});
```

Can you please check it out and get it fixed? Thx!

**Comment by pensierinmusica** [comment]
Maybe the problem comes from [`replacestream`](https://github.com/eugeneware/replacestream/) and is related to https://github.com/eugeneware/replacestream/issues/26

**Comment by shinnn** [comment]
@pensierinmusica No. `replacestream` is used [only when the stream-mode Vinyl files are passed](https://github.com/lazd/gulp-replace/blob/669219160fcc611707ababac7c117325967a7e98/index.js#L23).

**Comment by lazd** [comment]
Hey @pensierinmusica, long time no talk!

I wouldn't expect a JPEG to survive most replace operations, what are you trying to replace within it, metadata?

**Comment by pensierinmusica** [comment]
Hey Larry, great to hear from you!

Nope, it's just a file that is in a folder with other files, where some need to have strings replaced and some not. Should I simply exclude image files from the process? Cheers!

**Comment by lazd** [comment]
@pensierinmusica do you have [`skipBinary: true`](https://github.com/lazd/gulp-replace#optionsskipbinary) on ?

**Comment by pensierinmusica** [comment]
Nope, I didn't... now added it and it fixed the problem :) Thanks for pointing it out!

Do you think we should close this issue or further investigate why a regex like the one posted at the top breaks an image file going through `gulp-replace` without `skipBinary`?

**Comment by lazd** [comment]
@pensierinmusica if you want to take a look, I'd appreciate knowing why it happens!

**Comment by pensierinmusica** [comment]
It looks like the problem is generated by [line 29](https://github.com/lazd/gulp-replace/blob/master/index.js#L29):

```js
file.contents = Buffer.from(String(file.contents).replace(search, replacement));
```

In particular by `String(file.contents)`. Apparently trying to cast a `Buffer` from a binary file to a `String` breaks it.

Give this, I wonder if it'd make sense for the library to always skip binary files.

What do you think?

**Comment by lazd** [comment]
1.0.0 released with `skipBinary: true` by default.
