### ISSUE TITLE
Please provide a Changelog

### ISSUE THREAD

**Issue by ncoden** [lazd/gulp-replace#94]
Hi, 👋 

It would be useful to get the list of changes and bugfixes between versions, with migrations notes or recommendations if any. For now we have to check in the code or git history if any change in the API was made, and it can take some time when you have a lot of dependencies to update.

Please publish a GitHub release for the last version `v1.0.0` with what changed and reasons behind the major version update, and provide a `CHANGELOG.md` file or GitHub releases.

See for example https://gist.github.com/ungoldman/476a87abd16cd970bb9f

Thank you. ❤️

**Comment by lazd** [comment]
Thanks, I forgot to do so!

https://github.com/lazd/gulp-replace/releases/tag/v1.0.0
