### ISSUE TITLE
error when replace file have '$' charter.

### ISSUE THREAD

**Issue by emaza** [lazd/gulp-replace#97]
Hi,
I have a error when I try to replace from file who have charters dollar with single quote like this: '$'.
If i change to double quotes it works.

```
const CONFIGReplaceUtils = new RegExp('<!-- gulpReplace:utils -->(.*?)<!-- gulpReplace:utils END -->', 'g')

gulp.task('watch', function () {
    // Callback mode, useful if any plugin in the pipeline depends on the `end`/`flush` event
    return gulp.src('./src/index.js')
       .pipe(replace(CONFIGReplaceUtils, fs.readFileSync('./src/utils.js', 'utf8')))
       .pipe('dist'))
})
```

File './src/utils.js'

```
var dolar = '$';
var other = 'will not be replace!!!!';
```

File './src/index.js'

`/* gulpReplace:utils */   /* gulpReplace:utils END */`

enviormet:
Ubuntu 16.04
node -v  v8.11.2
npm -v 5.6.0
"gulp": "^3.9.1"
"gulp-replace": "^1.0.0"

Thanks

**Comment by lazd** [comment]
Wait so like, you can't add content in that has a singlequote? Have you tried just using a string literal instead of reading the file in? Dumping the read file contents to make sure it's reading? Honestly this is baffling.
